# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0db2b0de0771ff8a28d07e0d86266911f49fa5f65b59e27743cd68fe0220b27a9f72dd810bf914c18d949a35e56b5c4f4e60c0f0e33abd48fe61a7647b2809e6

test:
  secret_key_base: b44091ee44709eff3295a1b10c29e099afa3d3dd06c6fa5527a1796562f28955462e96842e5261904dbfd0acc2f5e28e0ca32caaac31e16a79f027905a672358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
